[package]
name = "libvmaf-sys"
version = "0.1.5"
edition = "2021"
description = "Library bindings for Netflix's VMAF"
license = "MIT"
repository = "https://github.com/ThatNerdUKnow/libvmaf-sys"
authors = ["Brandon Piña"]
include = ["**/*.rs","Cargo.toml","Cargo.lock","vmaf/libvmaf","vmaf/model"]
readme = "readme.md"
keywords = ["vmaf","video"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[build-dependencies]
meson-next = "1.0.1"
bindgen = "0.61.0"
