[package]
name = "libvmaf-sys"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[build-dependencies]
meson = "1.0.0"
bindgen = "0.61.0"